const API_BASE_URL_DEVELOPMENT = "https://localhost:7183";
const API_BASE_URL_PRODUCTION =
  "https://coursesapplication-aspnetserver.azurewebsites.net";

const ENDPOINTS = {
  GET_ALL_APPLICATIONS: "api/Application/GetApplications",
  GET_APPLICATION_BY_ID: "api/Application/GetApplication",
  PUT_APPLICATION: "api/Application/PutApplication",
  POST_APPLICATION: "api/Application/PostApplication",
  DELETE_APPLICATION: "api/Application/DeleteApplication",
};

const development = {
  API_URL_GET_ALL_APPLICATIONS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_APPLICATIONS}`,
  API_URL_GET_APPLICATION_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_APPLICATION_BY_ID}`,
  API_URL_PUT_APPLICATION: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.PUT_APPLICATION}`,
  API_URL_POST_APPLICATION: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.POST_APPLICATION}`,
  API_URL_DELETE_APPLICATION: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_APPLICATION}`,
};

const production = {
  API_URL_GET_ALL_APPLICATIONS: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_ALL_APPLICATIONS}`,
  API_URL_GET_APPLICATION_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_APPLICATION_BY_ID}`,
  API_URL_PUT_APPLICATION: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.PUT_APPLICATION}`,
  API_URL_POST_APPLICATION: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.POST_APPLICATION}`,
  API_URL_DELETE_APPLICATION: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.DELETE_APPLICATION}`,
};

const Constants =
  process.env.NODE_ENV === "development" ? development : production;

export default Constants;
